language: csharp
dist: trusty
mono: none
dotnet: 2.1.300-rc1-008673
install:
- dotnet restore --configfile NuGet.config
script:
- dotnet build -c Release
- dotnet test --no-build Tests/Tests.csproj -c Release
